int_value1 = 0
int_value2 = int()
int_value3 = int(9)
type(int_value1)
type(int_value2)
type(int_value3)
print(int_value1)
print(int_value2)
print(int_value3)
list_value1 = []
list_value2 = list()
list_value3 = list(('松田', '浅木'))
# list_value4 = list('松田', '浅木')
type(list_value1)
type(list_value2)
type(list_value3)
# type(list_value4)
print(list_value1)
print(list_value2)
print(list_value3)
# print(list_value4)